FROM golang:1.13-alpine AS client-builder

RUN apk --no-cache add make
WORKDIR /go/src/github.com/theoptz/grpcchat

COPY go.mod go.sum ./
RUN go mod download

COPY . .
ENV CGO_ENABLED=0
RUN make client

FROM scratch

WORKDIR /go/src/github.com/theoptz/grpcchat/
COPY --from=client-builder /go/src/github.com/theoptz/grpcchat/cmd/client/client ./cmd/client/client
CMD ["./cmd/client/client", "-a=127.0.0.1:8080", "-d=true"]