version: "3"

services:
  client:
    environment:
      - CHATNAME="${CHATNAME}"
    command: ./cmd/client/client -a=127.0.0.1:8080 -d=true -n=${CHATNAME}
    build:
      context: .
      dockerfile: Dockerfile-client
    network_mode: host
    stdin_open: true
